name: Lolalita
favicon: null
layout_spectrum: 0.23351
typography_spectrum: 0.50955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a9dbfb'
    - '#1d1f1e'
    - '#646560'
    - '#bc8064'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
