name: Lolalita
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7ea1b9'
    - '#e7eff1'
    - '#426981'
    - '#0a0c0f'
    - '#004163'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
